// Data definisi semua pertemuan praktikum
// Judul, deskripsi, tujuan, dan subtopik terstruktur tanpa label artificial "Langkah X"

export interface SubTopik {
  id: string;
  judul: string;
  level?: 2 | 3;
}

export interface Pertemuan {
  nomor: number;
  judul: string;
  subjudul: string;
  deskripsi: string;
  durasi: string;
  tujuan: string[];
  tersedia: boolean;
  subTopik: SubTopik[];
}

export const daftarPertemuan: Pertemuan[] = [
  {
    nomor: 1,
    judul: "JavaScript Dasar",
    subjudul: "Mengenal dasar-dasar JavaScript dan konsep pemrograman web",
    deskripsi:
      "Variabel, tipe data, struktur kondisional, loop, fungsi, event handler, array, objek, DOM manipulation, dan Fetch API.",
    durasi: "2 × 50 menit",
    tujuan: [
      "Memahami konsep dasar JavaScript sebagai bahasa pemrograman web",
      "Menguasai penggunaan variabel, tipe data, dan operator dalam JavaScript",
      "Mengimplementasikan struktur kendali (conditionals dan loops)",
      "Membuat dan menggunakan fungsi dalam JavaScript",
      "Mengerti cara menangani event dan memanipulasi DOM",
    ],
    tersedia: true,
    subTopik: [
      { id: "dasar-teori", judul: "JavaScript Dasar", level: 2 },
      { id: "variabel-kondisional", judul: "Variabel & Kondisional", level: 3 },
      { id: "membuat-file-javascript-pertama", judul: "Membuat File JavaScript Pertama", level: 3 },
      { id: "mengenal-variabel-dan-output", judul: "Mengenal Variabel dan Output", level: 3 },
      { id: "implementasi-struktur-kondisional", judul: "Implementasi Struktur Kondisional", level: 3 },
      { id: "latihan", judul: "Latihan", level: 3 },
      { id: "loop-fungsi", judul: "Loop & Fungsi", level: 3 },
      { id: "menggunakan-loop", judul: "Menggunakan Loop", level: 3 },
      { id: "daftar-nilai-siswa", judul: "Daftar Nilai Siswa:", level: 3 },
      { id: "countdown", judul: "Countdown:", level: 3 },
      { id: "nilai-dengan-forof", judul: "Nilai dengan for...of:", level: 3 },
      { id: "fungsi-dan-event-handler", judul: "Fungsi dan Event Handler", level: 3 },
      { id: "latihan", judul: "Latihan", level: 3 },
      { id: "array-objek", judul: "Array & Objek", level: 3 },
      { id: "array-dan-metode-array", judul: "Array dan Metode Array", level: 3 },
      { id: "manipulasi-array", judul: "Manipulasi Array:", level: 3 },
      { id: "bekerja-dengan-objek", judul: "Bekerja dengan Objek", level: 3 },
      { id: "manipulasi-objek", judul: "Manipulasi Objek:", level: 3 },
      { id: "latihan", judul: "Latihan", level: 3 },
      { id: "dom-api", judul: "DOM & API", level: 3 },
      { id: "fetch-api-dan-asyncawait", judul: "Fetch API dan Async/Await", level: 3 },
      { id: "hasil-praktikum", judul: "Hasil Praktikum", level: 3 },
      { id: "tips-dan-best-practices", judul: "Tips dan Best Practices", level: 3 },
      { id: "latihan", judul: "Latihan", level: 3 },
      { id: "tugas-praktikum", judul: "Tugas Praktikum: Aplikasi Kasir &amp; Keranjang Belanja Sederhana (Mini POS)", level: 2 },
      { id: "skenario-amp-persyaratan-fitur", judul: "Skenario &amp; Persyaratan Fitur", level: 3 },
      { id: "kriteria-penilaian", judul: "Kriteria Penilaian", level: 3 },
      { id: "format-pengumpulan", judul: "Format Pengumpulan", level: 2 },
    ],
  },
  {
    nomor: 2,
    judul: "JavaScript Next Gen (ES6+)",
    subjudul:
      "Mengenal fitur modern JavaScript (ES6+) dan penerapannya dalam pengembangan web",
    deskripsi:
      "Let/const, arrow functions, template literals, destructuring, spread/rest, default parameters, class, modules, array methods modern, Promise, dan async/await.",
    durasi: "2 × 50 menit",
    tujuan: [
      "Memahami fitur-fitur modern JavaScript (ES6+)",
      "Menguasai penggunaan let dan const untuk deklarasi variabel",
      "Mengimplementasikan arrow functions dalam kode JavaScript",
      "Menerapkan destructuring, rest dan spread operators",
      "Menggunakan template literals dengan efektif",
      "Mengenal dan mengimplementasikan modules dan import/export",
      "Menguasai metode array modern dan higher-order functions",
      "Menggunakan Promise dan async/await untuk operasi asinkron",
    ],
    tersedia: true,
    subTopik: [
      { id: "dasar-teori", judul: "JavaScript Next Gen", level: 2 },
      { id: "setup-project", judul: "Setup Project", level: 3 },
      { id: "struktur-project", judul: "Struktur Project", level: 3 },
      { id: "langkah-langkah-setup", judul: "Langkah-Langkah Setup", level: 3 },
      { id: "membuat-file-html-dasar", judul: "Membuat File HTML Dasar", level: 3 },
      { id: "langkah-selanjutnya", judul: "Langkah Selanjutnya", level: 3 },
      { id: "let-const-dan-arrow-functions", judul: "Let, Const, dan Arrow Functions", level: 3 },
      { id: "let-dan-const", judul: "Let dan Const", level: 3 },
      { id: "perbedaan-var-let-dan-const", judul: "Perbedaan var, let, dan const", level: 3 },
      { id: "implementasi-di-appjs", judul: "Implementasi di app.js", level: 3 },
      { id: "best-practices", judul: "Best Practices", level: 3 },
      { id: "arrow-functions", judul: "Arrow Functions", level: 3 },
      { id: "sintaks-arrow-functions", judul: "Sintaks Arrow Functions", level: 3 },
      { id: "implementasi-arrow-functions", judul: "Implementasi Arrow Functions", level: 3 },
      { id: "perbedaan-dengan-regular-functions", judul: "Perbedaan dengan Regular Functions", level: 3 },
      { id: "template-literals", judul: "Template Literals", level: 3 },
      { id: "sintaks-dasar", judul: "Sintaks Dasar", level: 3 },
      { id: "implementasi-template-literals", judul: "Implementasi Template Literals", level: 3 },
      { id: "keuntungan-template-literals", judul: "Keuntungan Template Literals", level: 3 },
      { id: "update-mainjs", judul: "Update main.js", level: 3 },
      { id: "latihan", judul: "Latihan", level: 3 },
      { id: "destructuring-dan-operators", judul: "Destructuring dan Operators", level: 3 },
      { id: "destructuring", judul: "Destructuring", level: 3 },
      { id: "object-destructuring", judul: "Object Destructuring", level: 3 },
      { id: "array-destructuring", judul: "Array Destructuring", level: 3 },
      { id: "implementasi-destructuring", judul: "Implementasi Destructuring", level: 3 },
      { id: "spread-dan-rest-operators", judul: "Spread dan Rest Operators", level: 3 },
      { id: "spread-operator", judul: "Spread Operator", level: 3 },
      { id: "rest-parameter", judul: "Rest Parameter", level: 3 },
      { id: "implementasi-spread-dan-rest", judul: "Implementasi Spread dan Rest", level: 3 },
      { id: "perbedaan-spread-vs-rest", judul: "Perbedaan Spread vs Rest", level: 3 },
      { id: "update-mainjs", judul: "Update main.js", level: 3 },
      { id: "praktik-terbaik", judul: "Praktik Terbaik", level: 3 },
      { id: "latihan", judul: "Latihan", level: 3 },
      { id: "classes-dan-object-literals", judul: "Classes dan Object Literals", level: 3 },
      { id: "default-parameters", judul: "Default Parameters", level: 3 },
      { id: "perbandingan-dengan-es5", judul: "Perbandingan dengan ES5", level: 3 },
      { id: "implementasi-default-parameters", judul: "Implementasi Default Parameters", level: 3 },
      { id: "es6-classes", judul: "ES6 Classes", level: 3 },
      { id: "sintaks-dasar-class", judul: "Sintaks Dasar Class", level: 3 },
      { id: "inheritance-dengan-extends", judul: "Inheritance dengan extends", level: 3 },
      { id: "implementasi-classes", judul: "Implementasi Classes", level: 3 },
      { id: "enhanced-object-literals", judul: "Enhanced Object Literals", level: 3 },
      { id: "fitur-fitur-enhanced-object-literals", judul: "Fitur-fitur Enhanced Object Literals", level: 3 },
      { id: "implementasi-enhanced-object-literals", judul: "Implementasi Enhanced Object Literals", level: 3 },
      { id: "update-mainjs", judul: "Update main.js", level: 3 },
      { id: "praktik-terbaik", judul: "Praktik Terbaik", level: 3 },
      { id: "1-gunakan-default-parameters", judul: "1. Gunakan Default Parameters", level: 3 },
      { id: "2-class-untuk-domain-models", judul: "2. Class untuk Domain Models", level: 3 },
      { id: "3-property-shorthand-untuk-clean-code", judul: "3. Property Shorthand untuk Clean Code", level: 3 },
      { id: "latihan", judul: "Latihan", level: 3 },
      { id: "modern-array-methods", judul: "Modern Array Methods", level: 3 },
      { id: "higher-order-functions", judul: "Higher-Order Functions", level: 3 },
      { id: "keuntungan-array-methods-modern", judul: "Keuntungan Array Methods Modern", level: 3 },
      { id: "map-filter-dan-find", judul: "Map, Filter, dan Find", level: 3 },
      { id: "map-mengubah-elemen", judul: "map() - Mengubah Elemen", level: 3 },
      { id: "filter-memilih-elemen", judul: "filter() - Memilih Elemen", level: 3 },
      { id: "find-mencari-elemen-tunggal", judul: "find() - Mencari Elemen Tunggal", level: 3 },
      { id: "reduce-pisau-swiss-army", judul: "Reduce - Pisau Swiss Army", level: 3 },
      { id: "some-dan-every", judul: "Some dan Every", level: 3 },
      { id: "some-tes-jika-ada-yang-lulus", judul: "some() - Tes Jika Ada yang Lulus", level: 3 },
      { id: "every-tes-jika-semua-lulus", judul: "every() - Tes Jika Semua Lulus", level: 3 },
      { id: "rantai-method-method-chaining", judul: "Rantai Method (Method Chaining)", level: 3 },
      { id: "implementasi-array-methods", judul: "Implementasi Array Methods", level: 3 },
      { id: "fitur-array-lanjutan", judul: "Fitur Array Lanjutan", level: 3 },
      { id: "arrayfrom", judul: "Array.from()", level: 3 },
      { id: "arrayof", judul: "Array.of()", level: 3 },
      { id: "flat-dan-flatmap", judul: "flat() dan flatMap()", level: 3 },
      { id: "includes", judul: "includes()", level: 3 },
      { id: "implementasi-advanced-arrays", judul: "Implementasi Advanced Arrays", level: 3 },
      { id: "update-mainjs", judul: "Update main.js", level: 3 },
      { id: "tabel-perbandingan", judul: "Tabel Perbandingan", level: 3 },
      { id: "praktik-terbaik", judul: "Praktik Terbaik", level: 3 },
      { id: "1-pilih-method-yang-tepat", judul: "1. Pilih Method yang Tepat", level: 3 },
      { id: "2-gunakan-chaining-dengan-bijak", judul: "2. Gunakan Chaining dengan Bijak", level: 3 },
      { id: "3-hindari-efek-samping-dalam-methods", judul: "3. Hindari Efek Samping dalam Methods", level: 3 },
      { id: "latihan", judul: "Latihan", level: 3 },
      { id: "async-programming", judul: "Async Programming", level: 3 },
      { id: "pengenalan-asynchronous-programming", judul: "Pengenalan Asynchronous Programming", level: 3 },
      { id: "mengapa-perlu-async", judul: "Mengapa Perlu Async?", level: 3 },
      { id: "promises", judul: "Promises", level: 3 },
      { id: "status-promise", judul: "Status Promise", level: 3 },
      { id: "membuat-promise", judul: "Membuat Promise", level: 3 },
      { id: "menggunakan-promises", judul: "Menggunakan Promises", level: 3 },
      { id: "method-promise", judul: "Method Promise", level: 3 },
      { id: "promiseall", judul: "Promise.all()", level: 3 },
      { id: "promiserace", judul: "Promise.race()", level: 3 },
      { id: "promiseallsettled", judul: "Promise.allSettled()", level: 3 },
      { id: "promiseany", judul: "Promise.any()", level: 3 },
      { id: "implementasi-promises", judul: "Implementasi Promises", level: 3 },
      { id: "asyncawait", judul: "Async/Await", level: 3 },
      { id: "sintaks-dasar", judul: "Sintaks Dasar", level: 3 },
      { id: "penanganan-error-dengan-trycatch", judul: "Penanganan Error dengan try/catch", level: 3 },
      { id: "eksekusi-paralel", judul: "Eksekusi Paralel", level: 3 },
      { id: "implementasi-asyncawait", judul: "Implementasi Async/Await", level: 3 },
      { id: "update-mainjs", judul: "Update main.js", level: 3 },
      { id: "perbandingan-callbacks-vs-promises-vs-asyncawait", judul: "Perbandingan: Callbacks vs Promises vs Async/Await", level: 3 },
      { id: "praktik-terbaik", judul: "Praktik Terbaik", level: 3 },
      { id: "1-selalu-tangani-error", judul: "1. Selalu Tangani Error", level: 3 },
      { id: "2-gunakan-promiseall-untuk-operasi-independen", judul: "2. Gunakan Promise.all untuk Operasi Independen", level: 3 },
      { id: "3-hindari-mencampur-promises-dan-asyncawait", judul: "3. Hindari Mencampur Promises dan Async/Await", level: 3 },
      { id: "4-kembalikan-promises-dari-fungsi-async", judul: "4. Kembalikan Promises dari Fungsi Async", level: 3 },
      { id: "kapan-menggunakan-apa", judul: "Kapan Menggunakan Apa?", level: 3 },
      { id: "testing-kode-async", judul: "Testing Kode Async", level: 3 },
      { id: "pertimbangan-performa", judul: "Pertimbangan Performa", level: 3 },
      { id: "1-hindari-await-yang-tidak-perlu", judul: "1. Hindari await yang Tidak Perlu", level: 3 },
      { id: "2-gunakan-promiseall-untuk-operasi-independen", judul: "2. Gunakan Promise.all untuk Operasi Independen", level: 3 },
      { id: "3-pertimbangkan-caching", judul: "3. Pertimbangkan Caching", level: 3 },
      { id: "dukungan-browser", judul: "Dukungan Browser", level: 3 },
      { id: "ringkasan", judul: "Ringkasan", level: 3 },
      { id: "poin-penting", judul: "Poin Penting", level: 3 },
      { id: "langkah-selanjutnya", judul: "Langkah Selanjutnya", level: 3 },
      { id: "latihan", judul: "Latihan", level: 3 },
    ],
  },
  {
    nomor: 3,
    judul: "React Basics",
    subjudul:
      "Memahami konsep dasar React dan membangun aplikasi interaktif dengan Component-Based Architecture",
    deskripsi:
      "Functional components, hooks (useState/useEffect), props, event handling, conditional rendering, React Router, custom hooks, Context API, dan testing dengan Jest.",
    durasi: "2 × 50 menit",
    tujuan: [
      "Memahami filosofi dan konsep dasar React (Component-Based Architecture)",
      "Membuat dan menggunakan functional components dengan hooks",
      "Mengelola state dan props dalam aplikasi React",
      "Menerapkan event handling dan conditional rendering",
      "Membuat form interaktif dengan controlled components",
      "Mengelola daftar data dengan keys dan rendering lists",
      "Memahami lifecycle components melalui useEffect",
      "Mengimplementasikan routing dasar dengan React Router",
    ],
    tersedia: true,
    subTopik: [
      { id: "dasar-teori", judul: "Konsep Dasar React", level: 2 },
      { id: "alat-bahan", judul: "Alat dan Bahan", level: 2 },
      { id: "panduan-praktik", judul: "Langkah Praktikum", level: 2 },
      { id: "setup-react", judul: "1. Setup Project React", level: 3 },
      { id: "komponen-pertama", judul: "2. Membuat Komponen React (Components & Props)", level: 3 },
      { id: "state-hooks", judul: "3. Manajemen State dengan Hooks", level: 3 },
      { id: "react-routing", judul: "4. Routing dengan React Router", level: 3 },
      { id: "custom-hook", judul: "5. Pembuatan Custom Hook", level: 3 },
      { id: "context-api", judul: "6. Global State dengan Context API", level: 3 },
      { id: "testing-jest", judul: "7. Testing dengan Jest &amp; RTL", level: 3 },
      { id: "tugas-praktikum", judul: "Tugas: Manajemen Buku Pribadi", level: 2 },
      { id: "format-pengumpulan", judul: "Format Pengumpulan", level: 2 },
    ],
  },
  {
    nomor: 4,
    judul: "Python Dasar",
    subjudul: "Mengenal dasar-dasar Python dan pemrograman berbasis objek",
    deskripsi:
      "Variabel dan tipe data Python, operator, struktur kendali, loop, fungsi, list, dictionary, set, dan penggunaan modul Python.",
    durasi: "2 × 50 menit",
    tujuan: [
      "Memahami konsep dasar Python sebagai bahasa pemrograman",
      "Menguasai penggunaan variabel, tipe data, dan operator dalam Python",
      "Mengimplementasikan struktur kendali (conditionals dan loops)",
      "Membuat dan menggunakan fungsi dalam Python",
      "Bekerja dengan koleksi data seperti list, dictionary, dan set",
    ],
    tersedia: true,
    subTopik: [
      { id: "dasar-teori", judul: "Python Dasar", level: 2 },
      { id: "pengenalan-python", judul: "Pengenalan Python", level: 3 },
      { id: "apa-itu-python", judul: "Apa itu Python?", level: 3 },
      { id: "implementasi-python", judul: "Implementasi Python", level: 3 },
      { id: "instalasi-python", judul: "Instalasi Python", level: 3 },
      { id: "cek-instalasi-python", judul: "Cek Instalasi Python", level: 3 },
      { id: "install-python-jika-belum-ada", judul: "Install Python (jika belum ada)", level: 3 },
      { id: "program-python-pertama", judul: "Program Python Pertama", level: 3 },
      { id: "membuat-file-python", judul: "Membuat File Python", level: 3 },
      { id: "menjalankan-program", judul: "Menjalankan Program", level: 3 },
      { id: "python-interactive-mode", judul: "Python Interactive Mode", level: 3 },
      { id: "indentasi-di-python", judul: "Indentasi di Python", level: 3 },
      { id: "print-function", judul: "Print Function", level: 3 },
      { id: "komentar-di-python", judul: "Komentar di Python", level: 3 },
      { id: "python-zen", judul: "Python Zen", level: 3 },
      { id: "setup-ideeditor", judul: "Setup IDE/Editor", level: 3 },
      { id: "visual-studio-code", judul: "Visual Studio Code", level: 3 },
      { id: "pycharm", judul: "PyCharm", level: 3 },
      { id: "latihan", judul: "Latihan", level: 3 },
      { id: "variabel-tipe-data", judul: "Variabel & Tipe Data", level: 3 },
      { id: "variabel-di-python", judul: "Variabel di Python", level: 3 },
      { id: "tipe-data-dasar", judul: "Tipe Data Dasar", level: 3 },
      { id: "memeriksa-tipe-data", judul: "Memeriksa Tipe Data", level: 3 },
      { id: "konversi-tipe-data-type-casting", judul: "Konversi Tipe Data (Type Casting)", level: 3 },
      { id: "operator", judul: "Operator", level: 3 },
      { id: "operator-aritmatika", judul: "Operator Aritmatika", level: 3 },
      { id: "operator-perbandingan", judul: "Operator Perbandingan", level: 3 },
      { id: "operator-logika", judul: "Operator Logika", level: 3 },
      { id: "operator-assignment", judul: "Operator Assignment", level: 3 },
      { id: "string-formatting", judul: "String Formatting", level: 3 },
      { id: "input-dan-output", judul: "Input dan Output", level: 3 },
      { id: "naming-conventions", judul: "Naming Conventions", level: 3 },
      { id: "latihan", judul: "Latihan", level: 3 },
      { id: "struktur-kendali", judul: "Struktur Kendali", level: 3 },
      { id: "percabangan-if-else", judul: "Percabangan (If-Else)", level: 3 },
      { id: "if-statement", judul: "If Statement", level: 3 },
      { id: "if-else", judul: "If-Else", level: 3 },
      { id: "if-elif-else", judul: "If-Elif-Else", level: 3 },
      { id: "nested-if", judul: "Nested If", level: 3 },
      { id: "ternary-operator", judul: "Ternary Operator", level: 3 },
      { id: "logical-operators-dalam-kondisi", judul: "Logical Operators dalam Kondisi", level: 3 },
      { id: "perulangan-loops", judul: "Perulangan (Loops)", level: 3 },
      { id: "for-loop", judul: "For Loop", level: 3 },
      { id: "while-loop", judul: "While Loop", level: 3 },
      { id: "break-dan-continue", judul: "Break dan Continue", level: 3 },
      { id: "nested-loops", judul: "Nested Loops", level: 3 },
      { id: "loop-dengan-else", judul: "Loop dengan Else", level: 3 },
      { id: "list-comprehension", judul: "List Comprehension", level: 3 },
      { id: "contoh-program-lengkap", judul: "Contoh Program Lengkap", level: 3 },
      { id: "latihan", judul: "Latihan", level: 3 },
      { id: "fungsi", judul: "Fungsi", level: 3 },
      { id: "apa-itu-fungsi", judul: "Apa itu Fungsi?", level: 3 },
      { id: "membuat-fungsi-dasar", judul: "Membuat Fungsi Dasar", level: 3 },
      { id: "fungsi-dengan-parameter", judul: "Fungsi dengan Parameter", level: 3 },
      { id: "parameter-default", judul: "Parameter Default", level: 3 },
      { id: "return-statement", judul: "Return Statement", level: 3 },
      { id: "keyword-arguments", judul: "Keyword Arguments", level: 3 },
      { id: "variable-length-arguments", judul: "Variable-Length Arguments", level: 3 },
      { id: "lambda-functions", judul: "Lambda Functions", level: 3 },
      { id: "scope-variabel", judul: "Scope Variabel", level: 3 },
      { id: "docstrings", judul: "Docstrings", level: 3 },
      { id: "higher-order-functions", judul: "Higher-Order Functions", level: 3 },
      { id: "recursion", judul: "Recursion", level: 3 },
      { id: "best-practices", judul: "Best Practices", level: 3 },
      { id: "latihan", judul: "Latihan", level: 3 },
      { id: "struktur-data", judul: "Struktur Data", level: 3 },
      { id: "struktur-data-di-python", judul: "Struktur Data di Python", level: 3 },
      { id: "list", judul: "List", level: 3 },
      { id: "membuat-dan-mengakses-list", judul: "Membuat dan Mengakses List", level: 3 },
      { id: "slicing-list", judul: "Slicing List", level: 3 },
      { id: "memodifikasi-list", judul: "Memodifikasi List", level: 3 },
      { id: "metode-list", judul: "Metode List", level: 3 },
      { id: "list-comprehension", judul: "List Comprehension", level: 3 },
      { id: "nested-lists", judul: "Nested Lists", level: 3 },
      { id: "dictionary", judul: "Dictionary", level: 3 },
      { id: "membuat-dan-mengakses-dictionary", judul: "Membuat dan Mengakses Dictionary", level: 3 },
      { id: "memodifikasi-dictionary", judul: "Memodifikasi Dictionary", level: 3 },
      { id: "metode-dictionary", judul: "Metode Dictionary", level: 3 },
      { id: "iterasi-dictionary", judul: "Iterasi Dictionary", level: 3 },
      { id: "dictionary-comprehension", judul: "Dictionary Comprehension", level: 3 },
      { id: "nested-dictionaries", judul: "Nested Dictionaries", level: 3 },
      { id: "tuple", judul: "Tuple", level: 3 },
      { id: "set", judul: "Set", level: 3 },
      { id: "set-operations-matematika", judul: "Set Operations (Matematika)", level: 3 },
      { id: "konversi-antar-struktur-data", judul: "Konversi Antar Struktur Data", level: 3 },
      { id: "latihan", judul: "Latihan", level: 3 },
      { id: "modul-python", judul: "Modul Python", level: 3 },
      { id: "apa-itu-modul", judul: "Apa itu Modul?", level: 3 },
      { id: "membuat-modul-sendiri", judul: "Membuat Modul Sendiri", level: 3 },
      { id: "buat-file-modul", judul: "Buat File Modul", level: 3 },
      { id: "gunakan-modul", judul: "Gunakan Modul", level: 3 },
      { id: "jalankan-program", judul: "Jalankan Program", level: 3 },
      { id: "cara-import-modul", judul: "Cara Import Modul", level: 3 },
      { id: "module-search-path", judul: "Module Search Path", level: 3 },
      { id: "modul-built-in-python", judul: "Modul Built-in Python", level: 3 },
      { id: "module-math", judul: "Module math", level: 3 },
      { id: "module-random", judul: "Module random", level: 3 },
      { id: "module-datetime", judul: "Module datetime", level: 3 },
      { id: "module-os", judul: "Module os", level: 3 },
      { id: "module-sys", judul: "Module sys", level: 3 },
      { id: "package-kumpulan-modul", judul: "Package (Kumpulan Modul)", level: 3 },
      { id: "struktur-package", judul: "Struktur Package", level: 3 },
      { id: "buat-file-file-package", judul: "Buat File-file Package", level: 3 },
      { id: "gunakan-package", judul: "Gunakan Package", level: 3 },
      { id: "module-attributes", judul: "Module Attributes", level: 3 },
      { id: "if-name-main", judul: "if __name__ == \"__main__\"", level: 3 },
      { id: "installing-external-packages", judul: "Installing External Packages", level: 3 },
      { id: "contoh-penggunaan-external-package", judul: "Contoh Penggunaan External Package", level: 3 },
      { id: "best-practices", judul: "Best Practices", level: 3 },
      { id: "latihan", judul: "Latihan", level: 3 },
    ],
  },
  {
    nomor: 5,
    judul: "Python OOP",
    subjudul: "Pemrograman Berorientasi Objek dengan Python",
    deskripsi:
      "Class, object, inheritance, encapsulation, polymorphism, abstract class, dan implementasi sistem berbasis OOP di Python.",
    durasi: "2 × 50 menit",
    tujuan: [
      "Memahami konsep dasar Object-Oriented Programming (OOP)",
      "Mengimplementasikan Class dan Object dalam Python",
      "Menerapkan Atribut dan Metode dalam Class",
      "Menggunakan Constructor dan Self dalam Python",
      "Implementasi Inheritance (Pewarisan) antar Class",
      "Menerapkan Encapsulation dan Access Modifiers",
      "Memahami Polymorphism dan Method Overriding",
      "Implementasi Abstract Class dan Interface",
    ],
    tersedia: true,
    subTopik: [
      { id: "dasar-teori", judul: "Python OOP", level: 2 },
      { id: "pengenalan-oop", judul: "Pengenalan OOP", level: 3 },
      { id: "apa-itu-object-oriented-programming", judul: "Apa itu Object-Oriented Programming?", level: 3 },
      { id: "empat-pilar-oop", judul: "Empat Pilar OOP", level: 3 },
      { id: "1-encapsulation-enkapsulasi", judul: "1. Encapsulation (Enkapsulasi)", level: 3 },
      { id: "2-inheritance-pewarisan", judul: "2. Inheritance (Pewarisan)", level: 3 },
      { id: "3-polymorphism-polimorfisme", judul: "3. Polymorphism (Polimorfisme)", level: 3 },
      { id: "4-abstraction-abstraksi", judul: "4. Abstraction (Abstraksi)", level: 3 },
      { id: "keuntungan-menggunakan-oop", judul: "Keuntungan Menggunakan OOP", level: 3 },
      { id: "1-modular", judul: "1. Modular", level: 3 },
      { id: "2-reusability", judul: "2. Reusability", level: 3 },
      { id: "3-maintainability", judul: "3. Maintainability", level: 3 },
      { id: "4-scalability", judul: "4. Scalability", level: 3 },
      { id: "5-data-security", judul: "5. Data Security", level: 3 },
      { id: "kapan-menggunakan-oop", judul: "Kapan Menggunakan OOP?", level: 3 },
      { id: "python-dan-oop", judul: "Python dan OOP", level: 3 },
      { id: "contoh-sederhana", judul: "Contoh Sederhana", level: 3 },
      { id: "perbandingan-procedural-vs-oop", judul: "Perbandingan: Procedural vs OOP", level: 3 },
      { id: "pendekatan-procedural", judul: "Pendekatan Procedural", level: 3 },
      { id: "pendekatan-oop", judul: "Pendekatan OOP", level: 3 },
      { id: "kesimpulan", judul: "Kesimpulan", level: 3 },
      { id: "class-dan-object", judul: "Class dan Object", level: 3 },
      { id: "apa-itu-class", judul: "Apa itu Class?", level: 3 },
      { id: "apa-itu-object", judul: "Apa itu Object?", level: 3 },
      { id: "membuat-class-sederhana", judul: "Membuat Class Sederhana", level: 3 },
      { id: "sintaks-dasar-class", judul: "Sintaks Dasar Class", level: 3 },
      { id: "menambahkan-atribut-class", judul: "Menambahkan Atribut Class", level: 3 },
      { id: "constructor-method-init", judul: "Constructor: Method __init__", level: 3 },
      { id: "membuat-object-instance", judul: "Membuat Object (Instance)", level: 3 },
      { id: "menambahkan-method", judul: "Menambahkan Method", level: 3 },
      { id: "contoh-lengkap", judul: "Contoh Lengkap", level: 3 },
      { id: "perbedaan-class-attribute-vs-instance-attribute", judul: "Perbedaan Class Attribute vs Instance Attribute", level: 3 },
      { id: "special-methods-dunder-methods", judul: "Special Methods (Dunder Methods)", level: 3 },
      { id: "praktik-terbaik", judul: "Praktik Terbaik", level: 3 },
      { id: "1-naming-conventions", judul: "1. Naming Conventions", level: 3 },
      { id: "2-single-responsibility-principle", judul: "2. Single Responsibility Principle", level: 3 },
      { id: "3-documentation", judul: "3. Documentation", level: 3 },
      { id: "latihan", judul: "Latihan", level: 3 },
      { id: "inheritance-pewarisan", judul: "Inheritance (Pewarisan)", level: 3 },
      { id: "apa-itu-inheritance", judul: "Apa itu Inheritance?", level: 3 },
      { id: "konsep-dasar-inheritance", judul: "Konsep Dasar Inheritance", level: 3 },
      { id: "terminologi", judul: "Terminologi", level: 3 },
      { id: "hubungan-is-a", judul: "Hubungan \"is-a\"", level: 3 },
      { id: "implementasi-inheritance", judul: "Implementasi Inheritance", level: 3 },
      { id: "membuat-parent-class", judul: "Membuat Parent Class", level: 3 },
      { id: "membuat-child-class", judul: "Membuat Child Class", level: 3 },
      { id: "menggunakan-child-class", judul: "Menggunakan Child Class", level: 3 },
      { id: "method-overriding", judul: "Method Overriding", level: 3 },
      { id: "contoh-lengkap", judul: "Contoh Lengkap", level: 3 },
      { id: "multiple-inheritance", judul: "Multiple Inheritance", level: 3 },
      { id: "mengecek-inheritance", judul: "Mengecek Inheritance", level: 3 },
      { id: "praktik-terbaik", judul: "Praktik Terbaik", level: 3 },
      { id: "1-gunakan-super", judul: "1. Gunakan super()", level: 3 },
      { id: "2-liskov-substitution-principle", judul: "2. Liskov Substitution Principle", level: 3 },
      { id: "3-favor-composition-over-inheritance", judul: "3. Favor Composition Over Inheritance", level: 3 },
      { id: "design-patterns-dengan-inheritance", judul: "Design Patterns dengan Inheritance", level: 3 },
      { id: "template-method-pattern", judul: "Template Method Pattern", level: 3 },
      { id: "latihan", judul: "Latihan", level: 3 },
      { id: "encapsulation", judul: "Encapsulation", level: 3 },
      { id: "apa-itu-encapsulation", judul: "Apa itu Encapsulation?", level: 3 },
      { id: "access-modifiers-di-python", judul: "Access Modifiers di Python", level: 3 },
      { id: "public-attributes", judul: "Public Attributes", level: 3 },
      { id: "protected-attributes", judul: "Protected Attributes", level: 3 },
      { id: "private-attributes", judul: "Private Attributes", level: 3 },
      { id: "property-decorators", judul: "Property Decorators", level: 3 },
      { id: "getter-dengan-property", judul: "Getter dengan @property", level: 3 },
      { id: "setter-dengan-propertysetter", judul: "Setter dengan @property.setter", level: 3 },
      { id: "deleter-dengan-propertydeleter", judul: "Deleter dengan @property.deleter", level: 3 },
      { id: "contoh-lengkap-bank-account", judul: "Contoh Lengkap: Bank Account", level: 3 },
      { id: "kapan-menggunakan-access-modifiers", judul: "Kapan Menggunakan Access Modifiers", level: 3 },
      { id: "gunakan-public", judul: "Gunakan Public", level: 3 },
      { id: "gunakan-protected", judul: "Gunakan Protected", level: 3 },
      { id: "gunakan-private", judul: "Gunakan Private", level: 3 },
      { id: "praktik-terbaik", judul: "Praktik Terbaik", level: 3 },
      { id: "1-gunakan-properties-untuk-validasi", judul: "1. Gunakan Properties untuk Validasi", level: 3 },
      { id: "2-encapsulate-complex-logic", judul: "2. Encapsulate Complex Logic", level: 3 },
      { id: "3-dont-expose-mutable-collections", judul: "3. Don't Expose Mutable Collections", level: 3 },
      { id: "latihan", judul: "Latihan", level: 3 },
      { id: "polymorphism", judul: "Polymorphism", level: 3 },
      { id: "apa-itu-polymorphism", judul: "Apa itu Polymorphism?", level: 3 },
      { id: "jenis-jenis-polymorphism", judul: "Jenis-jenis Polymorphism", level: 3 },
      { id: "1-method-overriding", judul: "1. Method Overriding", level: 3 },
      { id: "2-duck-typing", judul: "2. Duck Typing", level: 3 },
      { id: "polymorphism-dengan-function", judul: "Polymorphism dengan Function", level: 3 },
      { id: "function-yang-polymorphic", judul: "Function yang Polymorphic", level: 3 },
      { id: "method-chaining-dengan-polymorphism", judul: "Method Chaining dengan Polymorphism", level: 3 },
      { id: "operator-overloading", judul: "Operator Overloading", level: 3 },
      { id: "common-operator-overloading-methods", judul: "Common Operator Overloading Methods", level: 3 },
      { id: "contoh-lengkap-payment-system", judul: "Contoh Lengkap: Payment System", level: 3 },
      { id: "polymorphism-dengan-built-in-functions", judul: "Polymorphism dengan Built-in Functions", level: 3 },
      { id: "praktik-terbaik", judul: "Praktik Terbaik", level: 3 },
      { id: "1-design-for-polymorphism", judul: "1. Design for Polymorphism", level: 3 },
      { id: "2-use-abstract-base-classes", judul: "2. Use Abstract Base Classes", level: 3 },
      { id: "3-follow-liskov-substitution-principle", judul: "3. Follow Liskov Substitution Principle", level: 3 },
      { id: "latihan", judul: "Latihan", level: 3 },
      { id: "abstract-class", judul: "Abstract Class", level: 3 },
      { id: "apa-itu-abstract-class", judul: "Apa itu Abstract Class?", level: 3 },
      { id: "module-abc-abstract-base-classes", judul: "Module ABC (Abstract Base Classes)", level: 3 },
      { id: "komponen-utama", judul: "Komponen Utama", level: 3 },
      { id: "membuat-abstract-class", judul: "Membuat Abstract Class", level: 3 },
      { id: "basic-abstract-class", judul: "Basic Abstract Class", level: 3 },
      { id: "concrete-implementation", judul: "Concrete Implementation", level: 3 },
      { id: "partial-implementation", judul: "Partial Implementation", level: 3 },
      { id: "abstract-properties", judul: "Abstract Properties", level: 3 },
      { id: "interface-pattern", judul: "Interface Pattern", level: 3 },
      { id: "contoh-lengkap-database-connection", judul: "Contoh Lengkap: Database Connection", level: 3 },
      { id: "abstract-static-methods-class-methods", judul: "Abstract Static Methods & Class Methods", level: 3 },
      { id: "praktik-terbaik", judul: "Praktik Terbaik", level: 3 },
      { id: "1-use-abstract-classes-untuk-shared-behavior", judul: "1. Use Abstract Classes untuk Shared Behavior", level: 3 },
      { id: "2-keep-abstract-classes-focused", judul: "2. Keep Abstract Classes Focused", level: 3 },
      { id: "3-document-abstract-methods", judul: "3. Document Abstract Methods", level: 3 },
      { id: "kapan-menggunakan-abstract-class", judul: "Kapan Menggunakan Abstract Class?", level: 3 },
      { id: "latihan", judul: "Latihan", level: 3 },
    ],
  },
  {
    nomor: 6,
    judul: "Pyramid Framework",
    subjudul: "Membuat Aplikasi CRUD Sederhana dengan Pyramid dan PostgreSQL",
    deskripsi:
      "Setup proyek Pyramid dengan cookiecutter, konfigurasi PostgreSQL, SQLAlchemy ORM, migrasi Alembic, CRUD views, dan pengujian REST API.",
    durasi: "2 × 50 menit",
    tujuan: [
      "Memahami konsep dasar Pyramid Framework dalam pengembangan web",
      "Menggunakan cookiecutter untuk membuat struktur proyek Pyramid",
      "Mengonfigurasi koneksi database PostgreSQL dengan SQLAlchemy",
      "Membuat model data menggunakan SQLAlchemy ORM",
      "Mengimplementasikan migrasi database dengan Alembic",
      "Membuat view dan route untuk operasi CRUD sederhana",
      "Mengembangkan aplikasi web CRUD pengelolaan data Mahasiswa",
    ],
    tersedia: true,
    subTopik: [
      { id: "dasar-teori", judul: "Python Pyramid", level: 2 },
      { id: "setup-environment", judul: "Setup Environment", level: 3 },
      { id: "persiapan-lingkungan-pengembangan", judul: "Persiapan Lingkungan Pengembangan", level: 3 },
      { id: "membuat-virtual-environment", judul: "Membuat Virtual Environment", level: 3 },
      { id: "instalasi-pyramid-dan-dependensi", judul: "Instalasi Pyramid dan Dependensi", level: 3 },
      { id: "membuat-proyek-pyramid-dengan-cookiecutter", judul: "Membuat Proyek Pyramid dengan Cookiecutter", level: 3 },
      { id: "menjalankan-cookiecutter", judul: "Menjalankan Cookiecutter", level: 3 },
      { id: "instalasi-dependensi-proyek", judul: "Instalasi Dependensi Proyek", level: 3 },
      { id: "struktur-direktori-proyek", judul: "Struktur Direktori Proyek", level: 3 },
      { id: "penjelasan-struktur-proyek", judul: "Penjelasan Struktur Proyek", level: 3 },
      { id: "file-konfigurasi-utama", judul: "File Konfigurasi Utama", level: 3 },
      { id: "direktori-penting", judul: "Direktori Penting", level: 3 },
      { id: "verifikasi-setup", judul: "Verifikasi Setup", level: 3 },
      { id: "langkah-selanjutnya", judul: "Langkah Selanjutnya", level: 3 },
      { id: "database-models", judul: "Database & Models", level: 3 },
      { id: "konfigurasi-database-postgresql", judul: "Konfigurasi Database PostgreSQL", level: 3 },
      { id: "pastikan-postgresql-sudah-terpasang", judul: "Pastikan PostgreSQL Sudah Terpasang", level: 3 },
      { id: "membuat-database-postgresql", judul: "Membuat Database PostgreSQL", level: 3 },
      { id: "install-dependensi-postgresql", judul: "Install Dependensi PostgreSQL", level: 3 },
      { id: "update-konfigurasi-pyramid", judul: "Update Konfigurasi Pyramid", level: 3 },
      { id: "membuat-model-mahasiswa", judul: "Membuat Model Mahasiswa", level: 3 },
      { id: "buat-file-model-mahasiswa", judul: "Buat File Model Mahasiswa", level: 3 },
      { id: "update-modelsinitpy", judul: "Update models/init.py", level: 3 },
      { id: "update-script-initialize-db", judul: "Update Script Initialize DB", level: 3 },
      { id: "menjalankan-migrasi-database-dengan-alembic", judul: "Menjalankan Migrasi Database dengan Alembic", level: 3 },
      { id: "pastikan-alembic-terpasang", judul: "Pastikan Alembic Terpasang", level: 3 },
      { id: "membuat-migrasi-awal", judul: "Membuat Migrasi Awal", level: 3 },
      { id: "menjalankan-migrasi", judul: "Menjalankan Migrasi", level: 3 },
      { id: "inisialisasi-database-dengan-data-awal", judul: "Inisialisasi Database dengan Data Awal", level: 3 },
      { id: "perintah-alembic-yang-berguna", judul: "Perintah Alembic yang Berguna", level: 3 },
      { id: "verifikasi-data-di-database", judul: "Verifikasi Data di Database", level: 3 },
      { id: "langkah-selanjutnya", judul: "Langkah Selanjutnya", level: 3 },
      { id: "views-routes", judul: "Views & Routes", level: 3 },
      { id: "membuat-views-untuk-crud-mahasiswa", judul: "Membuat Views untuk CRUD Mahasiswa", level: 3 },
      { id: "buat-file-views-mahasiswa", judul: "Buat File Views Mahasiswa", level: 3 },
      { id: "penjelasan-view-functions", judul: "Penjelasan View Functions", level: 3 },
      { id: "membuat-routes-dan-update-routespy", judul: "Membuat Routes dan Update routes.py", level: 3 },
      { id: "update-file-routespy", judul: "Update File routes.py", level: 3 },
      { id: "restful-api-pattern", judul: "RESTful API Pattern", level: 3 },
      { id: "scan-views-module", judul: "Scan Views Module", level: 3 },
      { id: "sqlalchemy-query-patterns", judul: "SQLAlchemy Query Patterns", level: 3 },
      { id: "menjalankan-aplikasi", judul: "Menjalankan Aplikasi", level: 3 },
      { id: "langkah-selanjutnya", judul: "Langkah Selanjutnya", level: 3 },
      { id: "testing", judul: "Testing", level: 3 },
      { id: "pengujian-api-dengan-curl", judul: "Pengujian API dengan curl", level: 3 },
      { id: "pengujian-dengan-curl-di-linuxmacos", judul: "Pengujian dengan curl di Linux/macOS", level: 3 },
      { id: "mendapatkan-daftar-mahasiswa-get", judul: "Mendapatkan Daftar Mahasiswa (GET)", level: 3 },
      { id: "mendapatkan-detail-mahasiswa-get", judul: "Mendapatkan Detail Mahasiswa (GET)", level: 3 },
      { id: "menambahkan-mahasiswa-baru-post", judul: "Menambahkan Mahasiswa Baru (POST)", level: 3 },
      { id: "mengupdate-data-mahasiswa-put", judul: "Mengupdate Data Mahasiswa (PUT)", level: 3 },
      { id: "menghapus-data-mahasiswa-delete", judul: "Menghapus Data Mahasiswa (DELETE)", level: 3 },
      { id: "pengujian-dengan-curl-di-windows", judul: "Pengujian dengan curl di Windows", level: 3 },
      { id: "alternatif-tools-untuk-pengujian-api", judul: "Alternatif Tools untuk Pengujian API", level: 3 },
      { id: "1-browser-untuk-get-request", judul: "1. Browser (untuk GET Request)", level: 3 },
      { id: "2-postman", judul: "2. Postman", level: 3 },
      { id: "3-insomnia", judul: "3. Insomnia", level: 3 },
      { id: "4-vs-code-rest-client-extension", judul: "4. VS Code REST Client Extension", level: 3 },
    ],
  },
  {
    nomor: 7,
    judul: "Basis Data + React Frontend",
    subjudul:
      "SQLAlchemy, Alembic, PostgreSQL, Pyramid + Bonus React Frontend",
    deskripsi:
      "Arsitektur MVC dengan service layer, schema validasi Marshmallow, REST API Products, dan bonus implementasi frontend React yang terhubung ke API Pyramid.",
    durasi: "2 × 50 menit",
    tujuan: [
      "Mempersiapkan lingkungan pengembangan dengan Python dan PostgreSQL",
      "Mengkonfigurasi koneksi basis data menggunakan SQLAlchemy",
      "Membuat dan mengelola model data menggunakan SQLAlchemy ORM",
      "Menerapkan migrasi basis data dengan Alembic",
      "Membuat layanan REST API dengan kerangka kerja Pyramid",
      "Mengintegrasikan model data dalam endpoint API",
      "Mengimplementasikan validasi data menggunakan Schema (Marshmallow)",
      "Membangun service layer untuk logika bisnis aplikasi",
    ],
    tersedia: true,
    subTopik: [
      { id: "dasar-teori", judul: "Arsitektur Backend & Database", level: 2 },
      { id: "paket-dibutuhkan", judul: "Paket & Dependensi Proyek", level: 2 },
      { id: "panduan-praktik", judul: "Langkah Praktikum", level: 2 },
      { id: "persiapan-backend", judul: "1. Inisialisasi Backend & Dependency", level: 3 },
      { id: "koneksi-database", judul: "2. Konfigurasi Database PostgreSQL", level: 3 },
      { id: "pemodelan-data", judul: "3. Pemodelan Entitas SQLAlchemy", level: 3 },
      { id: "migrasi-alembic", judul: "4. Migrasi Database dengan Alembic", level: 3 },
      { id: "validasi-schema", judul: "5. Validasi Schema Marshmallow", level: 3 },
      { id: "service-layer", judul: "6. Implementasi Service Layer", level: 3 },
      { id: "endpoint-produk", judul: "7. Pembuatan API Endpoints", level: 3 },
      { id: "pengujian-api", judul: "8. Pengujian & Validasi API", level: 3 },
      { id: "frontend-react", judul: "Bonus: Integrasi Frontend React", level: 2 },
      { id: "hasil-praktikum", judul: "Hasil Praktikum", level: 2 },
      { id: "format-pengumpulan", judul: "Format Pengumpulan", level: 2 },
    ],
  },
];

export function getPertemuan(nomor: number): Pertemuan | undefined {
  return daftarPertemuan.find((p) => p.nomor === nomor);
}

export function getPrevNext(nomor: number): {
  prev: Pertemuan | null;
  next: Pertemuan | null;
} {
  const idx = daftarPertemuan.findIndex((p) => p.nomor === nomor);
  return {
    prev: idx > 0 ? daftarPertemuan[idx - 1] : null,
    next:
      idx < daftarPertemuan.length - 1 ? daftarPertemuan[idx + 1] : null,
  };
}
